# Generated by Django 4.1 on 2022-08-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='lot',
            field=models.ForeignKey(db_column='lot', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='core.lot'),
            preserve_default=False,
        ),
    ]
