# Generated by Django 4.1 on 2022-08-30 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_bet_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='winner',
            field=models.ForeignKey(blank=True, db_column='winner', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
