# Generated by Django 4.1 on 2022-08-31 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lot_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='winner',
        ),
    ]
